### ISSUE TITLE
IBM Terraform configuration manager is listed twice in the UI

### ISSUE THREAD

**Issue by epostea** [ManageIQ/manageiq-providers-ibm_terraform#23]
Steps to reproduce the issue:
1. Go to Configuration Manager -> Providers and Add a new 'IBM Terraform' provider
2. The provider is added successfully, but it's displayed twice in the list

![Screen Shot 2020-09-11 at 9 55 27 AM](https://user-images.githubusercontent.com/22264185/92934286-4d80d200-f415-11ea-8557-7547a65b040a.png)

**Comment by k-chu** [comment]
@miq-bot add_reviewer @k-chu

**Comment by k-chu** [comment]
@miq-bot add_assign @k-chu 

We found the bug in ui-classic and will be raising a PR.
