### ISSUE TITLE
IBM Terraform provider for Kasparov

### ISSUE THREAD

**Issue by chadh1313** [ManageIQ/manageiq-providers-ibm_terraform#28]
**Planned for Kasparov (CP4MCM 2.2)**

- Create new plugin in ManageIQ
   - [x] https://github.com/ManageIQ/manageiq-providers-ibm_terraform
   - [x] convert as needed for pluggable config manager updates

- Define configuration manager with connection to CP4MCM Terraform (CAM)
   - [x] provider authentication: username, password, URL(s), check SSL - https://github.com/ManageIQ/manageiq-providers-ibm_terraform/pull/19
   - [x] associated UI and validation logic

- Discover and persist Terraform content in MIQ inventory
   - [x] templates (configuration profiles) - https://github.com/ManageIQ/manageiq-providers-ibm_terraform/pull/4,  https://github.com/ManageIQ/manageiq-providers-ibm_terraform/pull/25 and https://github.com/ManageIQ/manageiq-schema/pull/511
   - [x] managed virtual machines (configured systems) - https://github.com/ManageIQ/manageiq-providers-ibm_terraform/pull/20
   - [x] link (counterpart) to discovered VM in MIQ - https://github.com/ManageIQ/manageiq-providers-ibm_terraform/pull/21 and https://github.com/ManageIQ/manageiq-ui-classic/pull/7287

- Configuration Manager UI
   - [x] customize default views as needed - https://github.com/ManageIQ/manageiq-ui-classic/pull/7317
   - [x] add configured systems for all VMs under Terraform management
   - [x] Display Terraform resource type of VM
   - [x] [Provide link (launchout) to stack in IBM Terraform](https://github.com/ManageIQ/manageiq-providers-ibm_terraform/issues/36)
   - [x] Add icons for cloud types (represent which cloud a VM came from) - https://github.com/ManageIQ/manageiq-providers-ibm_terraform/pull/39
         - can include icons for non-discovered clouds

**Comment by k-chu** [comment]
- Define configuration manager with connection to CP4MCM Terraform (CAM)
   - [x] provider authentication: username, password, URL(s), check SSL - [PR-19](https://github.com/ManageIQ/manageiq-providers-ibm_terraform/pull/19)
   - [x] associated UI and validation logic

- Discover and persist Terraform content in MIQ inventory
   - [x] templates (configuration profiles) - [PR-4](https://github.com/ManageIQ/manageiq-providers-ibm_terraform/pull/4) and [PR-25](https://github.com/ManageIQ/manageiq-providers-ibm_terraform/pull/25)
   - [x] managed virtual machines (configured systems) - [PR-20](https://github.com/ManageIQ/manageiq-providers-ibm_terraform/pull/20)
   - [x] link (counterpart) to discovered VM in MIQ - [PR-21](https://github.com/ManageIQ/manageiq-providers-ibm_terraform/pull/21)

- Configuration Manager UI
   - [ ] customize default views as needed
   - [ ] add configured systems for all VMs under Terraform management
   - [ ] Display Terraform resource type of VM
   - [ ] Provide link (launchout) to stack in IBM Terraform
   - [ ] Add icons for cloud types (represent which cloud a VM came from)
         - can include icons for non-discovered clouds

**Comment by epostea** [comment]
Fix for the refresh worker: https://github.com/ManageIQ/manageiq-providers-ibm_terraform/pull/26

**Comment by epostea** [comment]
Add association between configured systems and configuration profiles: https://github.com/ManageIQ/manageiq-providers-ibm_terraform/pull/29

**Comment by k-chu** [comment]
**Customize default views as needed** - https://github.com/ManageIQ/manageiq-ui-classic/pull/7340 and https://github.com/ManageIQ/manageiq-ui-classic/pull/7352
**Provide link (launchout) to Templates in IBM Terraform** - https://github.com/ManageIQ/manageiq-ui-classic/pull/7371 and https://github.com/ManageIQ/manageiq/pull/20646
**Provide link (launchout) to stack in IBM Terraform** - https://github.com/ManageIQ/manageiq-ui-classic/pull/7420 and https://github.com/ManageIQ/manageiq/pull/20686
