### ISSUE TITLE
Provide link (launchout) to stack in IBM Terraform

### ISSUE THREAD

**Issue by epostea** [ManageIQ/manageiq-providers-ibm_terraform#36]
We would like to add a link from the configured systems to the stack so the user can navigate to the CAM UI and review the stack details (i.e. resources that are deployed as part of the stack, input and output parameters, etc) and run against the stack (i.e. plan/apply/destroy)

The stack details page url is something like: `https://{baseUrl}/cam/instances/#!/instanceDetails/{stackId}`
where `baseUrl` can be determined from the default endpoint.

We would need to save the `stack_id` and I think we have two options:
1. either we extend the configured_systems table or reuse an existing column (manager_ref?)
2. or we pull in the stacks and relate the configured_systems to those. Not sure if orchestration_stacks are something that makes sense for a configuration_manager though.

Related user story: https://github.com/ManageIQ/manageiq-providers-ibm_terraform/issues/28

cc: @Fryguy @agrare @chadh1313 @k-chu @blancett

**Comment by chadh1313** [comment]
For the short term, ideally we can add the stack reference somewhere in the configured systems table (option 1), either via re-use of a column or a new field.  We will need to have larger design/architecture discussions about the best way to represent stack data from CAM in the future.

**Comment by Fryguy** [comment]
As discussed, I think it makes more sense to start collecting stacks, then associate that configured system to the stack.  Then the console_url method on a configured_system would just be constructed from something like `self.orchestration_stack&.ems_ref`

**Comment by agrare** [comment]
Hey @epostea is this completed now?

**Comment by epostea** [comment]
@agrare yes, we can close the issue.
