### ISSUE TITLE
IBM Terraform provider v2 

### ISSUE THREAD

**Issue by epostea** [ManageIQ/manageiq-providers-ibm_terraform#55]
Support chargeback and policy for non discovered VMs

- [x] Extend the refresh logic to bring in the hardware information (cpu, size, operating system)  https://github.com/ManageIQ/manageiq-providers-ibm_terraform/pull/59
- [x] Decorate the Configured systems with the hardware information https://github.com/ManageIQ/manageiq-providers-ibm_terraform/pull/59
- [x] Change the chargeback and policy to work with Configured systems https://github.com/ManageIQ/manageiq/pull/21019
- [x] Add chargeback support for Configured Systems to the UI (https://github.com/ManageIQ/manageiq-ui-classic/pull/7628)

**Comment by epostea** [comment]
cc: @Fryguy @agrare @chadh1313 @k-chu @bhadrim

**Comment by k-chu** [comment]
Extend the refresh logic to bring in the hardware information (cpu, size, operating system - https://github.com/ManageIQ/manageiq-providers-ibm_terraform/pull/59
Decorate the Configured systems with the hardware information - https://github.com/ManageIQ/manageiq-providers-ibm_terraform/pull/59

**Comment by k-chu** [comment]
@miq-bot assign @k-chu
